chainapsis/keplr-chain-registry

cosmos/agoric.json
See https://github.com/chainapsis/keplr-wallet/pull/601#issuecomment-1363659579
=> fix: add coinGeckoId for IST

cosmos/stride.json
Adds stLUNA to `cosmos/stride.json`
=> Add Stride's stLUNA

cosmos/jackal.json
=> Update jackal gas prices

cosmos/migaloo.json
=> Update rpc and rest endpoints

cosmos/stargaze.json
according to stargaze [governance proposal 172 ](https://www.mintscan.io/stargaze/proposals/172) the min gas price required for the network will be increased to `1ustars`
=> udpate stargaze gas price

cosmos/atlantic.json
Adjusted Sei Testnet (atlantic-2) rpc/rest urls and added correct gas price steps.
=> Update Sei Testnet Rest/RPC urls and gas price steps

cosmos/kaiyo.json
kuji allows multiple tokens for fees.
=> feat: kaiyo/Kuji - add more fee coins

cosmos/axelar-dojo.json
=> Fix Arbitrum

cosmos/realionetwork_3301.json
this PR change order of Realio staking token, and add RIO coingeckoID
=> add realio coingeckoId

cosmos/secret.json
Implementing the result of governance proposal: https://dev.mintscan.io/secret/proposals/260 into wallets before asking nodes to change settings.
=> Update Fee steps for SecretNetwork

cosmos/centauri.json
This PR will update Endpoints for Composable
=> update endpoint for composable

cosmos/dydx-testnet.json
the new dydx testnet will be started at 2023-10-17T17:00:00Z
=> Update dydx testnet

cosmos/pio-testnet.json
change gasPriceStep to match the new gas prices put in place on pio testnet
=> Update pio-testnet gasPriceStep

cosmos/likecoin-mainnet.json
https://www.mintscan.io/likecoin/proposals/74
The likecoin community has pass a proposal that recommend all gas prices to be increased by 1000x
=> Update likecoin gas price step

cosmos/mocha.json
Matches https://github.com/chainapsis/keplr-chain-registry/pull/290
=> feat: update min gas price for mocha testnet

cosmos/tgrade-mainnet.json
tgrade is not a keplr native chain anymore, so change rpc/rest to public one.
=> Change tgrade rpc/rest to managed by public, not native

cosmos/iov-mainnet-ibc.json
starname is not a keplr native chain anymore, so change rpc/rest to public one.
=> Change starname rpc/rest to managed by public, not native

cosmos/emoney.json
emoney is not a keplr native chain anymore, so change rpc/rest to public one.
=> Change emoney rpc/rest to managed by public, not native

cosmos/secret.json
Enough validators switched for this to work without problems
https://www.mintscan.io/secret/proposals/289
=> Change Secret Fee thresholds

cosmos/arkeo.json
Fix typo in coin name & add t to bech32 config
=> Update to tarkeo

src/validate.ts
- Extracted chain ID parsing to a constant for improved code clarity
- Fixed the error message in chain identifier validation to accurately display the expected and actual values, enhancing debugging accuracy
- Optimized performance by reducing redundant parsing
=> fix(validation): swap expected/actual in chain id check

cosmos/phoenix.json
Gas Price has been reduced on the phoenix-1 network https://github.com/cosmos/chain-registry/blob/master/terra2/chain.json
=> Reduced gas price for Terra

cosmos/iov-mainnet-ibc.json
The old nodes are not working anymore
=> Update rpc, rest and nodeProvider

src/constants.ts
`nativeTestnetChainIdentifiers` 파일에 Persistence Testnet indentify를 추가합니다
=> add Persistence indentify in constants

cosmos/Neutaro.json
Change coinDenom from neutaro to $NTMPI. We do this so our token is displayed the same in keplr and on ETH.
=> Change coinDenom from neutaro to $NTMPI.

cosmos/Neutaro.json
=> Adding the website to Neutaro.json

cosmos/carbon.json
Increase SWTH gas price based on conversation with maintainers
=> Update SWTH gas price on Carbon

cosmos/bbn-test.json
Also, update the RPC / Node API links.
=> Babylon: Update testnet Chain ID

cosmos/archway.json
Updates to archway's price of gas based on the last update to the network's minimum price of gas https://www.mintscan.io/archway/proposals/36
=> Updates to archway's price of gas based on updated minimum price of gas

src/constants.ts
add seda-testnet-1 in constants file
=> [feat] add seda-testnet-1 in constants

cosmos/dhealth.json
=> Update dHealth Chain

cosmos/dhealth.json
Sorry for the change again. This is our final bid.
=> Update dHealth bip44 - final

.github/workflows/cron-job.yml, .github/workflows/deploy.yml, src/validate.ts
=> Change price query URL

cosmos/canto_7700.json
Updated canto RPC and REST to stable and working endpoints.
=> Update canto rpc and rest endpoints

cosmos/HICKORY.json
Please Update our HICKORY.json
=> Correct "bech32 prefix hic "

src/constants.ts
=> Support Seda

cosmos/source-testnet
Request to add the Source Blockchain Testnet
=> request to add the source-testnet

cosmos/dymension_1100.json
This reverts commit 99eeb3ae14eb85bc71825d3d3f9cddd4f37f3345.
=> Revert "Revert "Add dymension evm info (#615)""

cosmos/kaiyo.json
Added the coinGeckId for NAMI on Kujira.
=> Add coinGeckoId to NAMI on Kujira

cosmos/neutron.json
=> Update neutron.json (sin token)

src/constants.ts
add zeta testnet in nativeTestnetChainIdentifiers
=> [feat] add zeta testnet

cosmos/pryzm.json
This PR intends to update Pryzm fee currencies to add gas step values and remove the Pryzm token itself for now.
=> Update Pryzm fee currencies config

cosmos/shentu-2.2.json
sifchain is not a keplr native chain anymore, so change rpc/rest to public one.
=> Change shentu rpc/rest to managed by public, not native

cosmos/sifchain.json
sifchain is not a keplr native chain anymore, so change rpc/rest to public one.
=> Change sifchain rpc/rest to managed by public, not native 

cosmos/symphony-testnet.json
updating here to match 0.3 information
=> Symphony Testnet: Update to 0.3

cosmos/gitopia.json
kjnodes has discontinued their node. Use Polkachu as node provider for Gitopia
=> use Polkachu as node provider for Gitopia

cosmos/shido_9008.json
change shido swagger and tendermint RPC
=> feat:change shido swagge,evm and tendermint RPC

cosmos/injective.json
Added coinGeckoId to XIII on Injective
=> XIII coinGeckoId

cosmos/dhealth.json
Add alternative BIP44s to dHealth
=> Add alternative bip44s to dHealth

cosmos/Neutaro.json
=> Change endpoints in Neutaro.json

cosmos/titan-test.json
1. update titan chain-id
2. add tnt4 token
=> update titan chain info

server/src/index.ts
- The api is for searching chain list on address modal of extension.
> tony approved
=> Add chain search api route on server

server/src/index.ts
- This PR is part of https://github.com/chainapsis/keplr-wallet/pull/1257
=> Sort loaded chains by chain name on server

cosmos/ixo.json
=> Update post chain upgrade

cosmos/bbn-test.json
Updates the data of Babylon Testnet
Chain is paused at the moment and will be up with the Babylon Testnet launch
=> feat: Babylon Testnet update

cosmos/neutron.json
https://www.coingecko.com/en/coins/drop-staked-tia
=> Add dTIA coingecko id

cosmos/ixo.json
=> Capitalisation of chainName

cosmos/dungeon.json
=> Update Quasar🤖🧬🧠 api, rpc dungeon.json

cosmos/elys.json, src/constants.ts
=> Support Elys Network

cosmos/euphrates-0.5.0.json
Updates Babylon Euphrates Devnet chain info
=> feat: Babylon Euphrates Devnet update

cosmos/milkyway.json
Update `milkTIA` gasPriceStep value on `MilkyWay`
=> Update milkTIA gasPriceStep on MilkyWay

cosmos/korellia.json
This PR updates the fees of KYVE's devnet
=> chore: update korellia fees

cosmos/atomone.json
Minimum gas prices has been increased to 0.1uatone to mitigate spam by tx multi send
=> Update atomone min_gas_price

cosmos/core.json
should be merged when dashboard change is ready
=> Update Persistence -> Persistence One

cosmos/andromeda.json
- Update endpoints for andromeda mainnet
=> update: andromeda mainnet endpoints

cosmos/pion.json
cosmwasm를 neutron testnet에 추가합니다
=> [feat] add cosmwasm in features

cosmos/pion.json
뉴트론 testnet에 stake currency 추가
=> [feat] add stake currency in neutron testnet

cosmos/kaon.json, cosmos/kyve.json
Update gas prices for the KYVE testnet and mainnet for the upcomding KYVE v2 upgrade
=> chore: update kyve fees

cosmos/milkyway.json, src/constants.ts
=> [feat] modfy mikyway

cosmos/milkyway.json
=> [feat] add coinGeckoId

cosmos/xrplevm_1449000.json
fix coinType on XRPL EVM Testnet: 118 -> 60
=> fix-coinType

cosmos/hippo-protocol-testnet.json, cosmos/hippo-protocol.json
Change the profile of Hippo Protocol node provider.
=> Change Hippo Protocol Node Provider

cosmos/atomone.json, src/constants.ts
=> Support AtomOne

cosmos/emoney.json
there is no page with nickname [`validator_net`](https://twitter.com/validator_net)
=> [emoney]: delete website's link

cosmos/pryzm.json
This PR adds PRYZM token coingecko ID
=> Add coingecko ID for PRYZM token

cosmos/shentu-2.2.json
add gasPriceStep of Shentu chain
=> add gasPriceStep of Shentu chain
