chainapsis/keplr-chain-registry

cosmos/quicksilver.json

The quicksilver team is onboarding Cosmos zone this week. This PR adds qATOM to the quicksilver currencies array to display users' qATOM balance in the extension.

changes to add qATOM to quicksilver currency

---

cosmos/umee.json

This is in anticipation for umee to raise its minimum gas. Minimum gas on umee will be raised to .06 in the near future.

Change minimum gas fee for Umee

---

cosmos/ixo.json

ixo upgraded it's chain today with the following changes:
- chainId from ixo-4 to ixo-5

Upgrade from ixo-4 to ixo-5

---

cosmos/dyson-mainnet.json

The current api/rpc entries are not official and we're getting reports of errors in Discord. 
This PR updates the Dyson Protocol entry to the main official API provider

Update Dyson Protocol to use Official API/RPC Endpoints

---

cosmos/migaloo.json

The $WHALE token has been listed on [coingecko now](https://www.coingecko.com/en/coins/white-whale), so this PR fixes the coingecko id.

Add coingecko coin-id for Migaloo chain

---

cosmos/atlantic.json

Sei atlantic-2 has a global minimum gas fee of 3.5usei, so this PR is to bump the gas price steps for atlantic-2

Bumped gas fees in atlantic-2 to meet global minimum

---

cosmos/kaiyo.json

This PR requests to add MNTA as a currency to Kujira. MantaDAO is a swap router and DAO running on the Kujira mainnet.

Add MNTA to Kujira

---

cosmos/pulsar.json

Due to unforseen issues with support for only 1 testnet we have to delay the migration to pulsar-3 for the actively testing dApps.
Please merge when possible.

Revert Secret testnet to pulsar-2

---

cosmos/stride.json

Stride validators turned on fees as a result of a congested mempool. Fee tokens were specified as follows:
```
minimum-gas-prices = "0.0005ustrd,0.001stuosmo,0.0001stuatom,0.001ibc/D24B4564BCD51D3D02D9987D92571EAC5915676A9BD6D9B0C1D0254CB8A5EA34,0.0001ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2"
```

turn on fees stride

---

cosmos/likecoin-mainnet.json

min-gas-price of most validators would be at 10nanolike, having levels at 1, 2, 3 causes poor UX

Update likecoin gas price

---

cosmos/kava_2222.json

Will this make it so USDT with show up properly under Kava in Keplr wallet? (currently shows as 'erc20/tether/usdt')
I believe this is the denom on the Kava (IBC) side, and not too sure if it's meant to have a different denom on the Kava EVM side....

Update kava_2222.json - add USDT

---

cosmos/elgafar.json
src/constants.ts

- The file name and `testnetId` have typos, which is preventing the website linked to the testnet from running on the emulator. I will leave this PR to fix the problem.
- https://github.com/cosmos/chain-registry/blob/fa7ae5ff6dc510afdb953d7f7eca5d87040669aa/testnets/stargazetestnet/chain.json#L8

fix typo on stargaze testnet chain id

---

cosmos/pulsar.json

Now that we're no longer running 2 different testnet networks, please add the config for native support of pulsar-3

Secret Network pulsar-3 native support

---

cosmos/cudos.json

This PR simply changes the reference of the image for the token logo to the chain logo so that they match, as many other chains do. The parralax logo doesn't look as good, so switching it out. Thanks! :)

Change CUDOS token logo to chain.png

---

cosmos/source.json

Source now has an active Coingecko listing:
https://www.coingecko.com/en/coins/source

Update Coingecko ID source.json

---

cosmos/kaiyo.json

MNTA is now a popular accepted fee token on Kujira. This PR requests it be added as such for the Keplr dropdown..

Add MNTA as fee token to Kujira

---

cosmos/bitcanna.json
cosmos/chihuahua.json
cosmos/comdex.json
cosmos/fetchhub.json
cosmos/gitopia.json
cosmos/jackal.json

- Simple addition of the `coinImageUrl` variable on the `bitcanna` token https://github.com/chainapsis/keplr-chain-registry/pull/396/commits/6047399bd7aee344dacff24b205adf1bdec26530
- Simple addition of the `coinImageUrl` variable on the `chihuahua` token https://github.com/chainapsis/keplr-chain-registry/pull/396/commits/554e4b1091a75e2bde67b174604e747b10dfdad1
- Simple addition of the `coinImageUrl` variable on the `gitopia` token https://github.com/chainapsis/keplr-chain-registry/pull/396/commits/30f233e865bfe397a58fbaed4c56d53305de110b
- Simple addition of the `coinImageUrl` variable on the `fetchhub` token https://github.com/chainapsis/keplr-chain-registry/pull/396/commits/9c3d35f111c8a260134a5b27ef8273ea2f19f1ba
- Simple addition of the `coinImageUrl` variable on the `comdex` token …

Fix multi icons

---

cosmos/archway.json

The last [PR](https://github.com/chainapsis/keplr-chain-registry/pull/457) was created to give a buffer to the gas price as the initial [PR](https://github.com/chainapsis/keplr-chain-registry/pull/456) caused transactions to fail but the actual issue was that Keplr's node's min price of gas was not adjusted. These nodes have since been updated and therefore I want to update the price to be in line with the network's minimum.

Updates to archway's price of gas to be inline with the minimum price of gas

---

cosmos/lum-network.json

This little PR updates the public Lum Network's RPC urls following a recent infrastructure change, to ensure compatibility on Keplr wallet

Update lum-network.json RPC urls

---

cosmos/bitsong-2b.json

Galaxy Station uses coin type 118 for bitsong

added alt coin type 118 for bitsong

---

cosmos/umee.json

+ coin Name is `UX`, but the base denom is `uumee`
+ coingecko ID is `uxchain`: https://www.coingecko.com/en/coins/uxchain

Update coin name in umee.json

---

cosmos/fxcore.json

Reverts chainapsis/keplr-chain-registry#535
In order to ensure that users can send transactions normally, modifications have to be restored🙏
ref: https://github.com/chainapsis/keplr-wallet/issues/1089

Revert "Add evm info for fxcore"

---

cosmos/nyx.json

Adding `gasPriceStep` to tokens on NYX

nyx: add gas price steps

---

cosmos/atlantic.json

According to the gas proposal on the Sei chain, the global minimum gas price for atlantic-2 has been bumped to 0.08 in order to even out gas prices between EVM and Cosmos transactions on Sei v2.
See the official Sei chain registry for confirmation of change or the Sei proposals.
https://github.com/sei-protocol/chain-registry/pull/58/files

Sei Testnet: Update Global Min Gas Price

---

cosmos/pirin.json

The currently used endpoints are rate limited and the nodes are pruned. I am replacing them with the official nolus endpoints which provide higher availability.

Replace nolus rpc endpoint

---

cosmos/self.json

Based on the code from Celestia, we have added `coinImageUrl` into the JSON in various locations so that the SLF icon shows properly. Currently, it does not display when added.

Update Self Chain (SLF) coinImageUrl.

---

cosmos/gravity-bridge.json

gravitybridge is not a keplr native chain anymore, so change rpc/rest to public one.

Change gravitybridge rpc/rest to managed by public, not native

---

cosmos/gitopia.json

gitopia is not a keplr native chain anymore, so change rpc/rest to public one.

Change gitopia rpc/rest to managed by public, not native

---

cosmos/umee.json

The current low gas setting, specifically, is below the 0.1uumee value that all validators were asked to enforce awhile back, and the sdk reports insufficient fees for borrow / repay transactions.  I'm ambivalent when it comes to updating the average & high settings and have just done so to match the chain-registry repo.  Can omit those changes – just let me know.

umee: update gas prices to mirror cosmos/chain-registry

---

cosmos/stride.json

All this does is pull in the upstream values from cosmos/chain-registry.
Should we publish the non-native / IBC denoms defined here in chain-registry?

stride: update gas prices to mirror cosmos/chain-registry

---

cosmos/akashnet.json

Just as an aside here, Akash is one of a handful of chains where I recently struggle to initiate transactions directly through the wallet.  Stride is another that comes to mind.  I'm checking in the static gas prices from chain-registry here in case it has some UX impact, but perhaps the RPC layer behind `rpc-akash.keplr.app` needs some love?

akash: add gas prices from cosmos/chain-registry

---

cosmos/pryzm.json

This PR intends to add Drop Protocol's dATOM token to the list of Pryzm's supported fee currencies.

Add dATOM to Pryzm fee currencies

---

cosmos/gravity-bridge.json

This patch updates the Gravity Bridge rpc and rest nodes from StakeTab to Polkachu as the StakeTab nodes have not been reliable recently.

Update Gravity Bridge rpc node

---

cosmos/mars.json

- use more stable endpoinst for users undelegate their assets without any problems before mars protocol support ends
- https://mars-rpc.publicnode.com/

Change mars protocol endpoints to publicnode

---

server/src/index.ts

- 익스텐션에서 요청을 보내 체인을 검색할 때, 체인 정보에서 모든 currencies의 denom을 가져와 검색어가 포함된 체인을 반환하게 되면 너무나도 많은 체인이 한번에 반환되므로, 다음과 같이 각 체인별로 사용할 denom을 제한합니다.
- cosmos: stakeCurrency의 denom을 사용. stakeCurrency가 없는 경우, currencies의 첫번째 항목의 denom을 사용.
- ethereum: currencies의 첫번째 항목의 denom을 사용. (일반적으로 ETH 또는 체인의 main currency)
- 또한 필터링 옵션으로 `chainNameAndToken`을 추가하여 체인 이름 및 제한된 자산 denom과 매칭되는 체인 리스트만 보여줍니다.
| tony approved

Search chains by stake currency or main currency denom on server

---

cosmos/diamond.json
cosmos/gardia.json

This PR updates the imageurls for `gardia.json` and `zenrock.json` and adds the coingeckoId for mainnet

add zenrock imageurl

---

cosmos/gardia.json

This PR updates gardia's chain-id from `gardia-2` to `gardia-3`.

update gardia chain-id

---

cosmos/manifest-ledger-testnet.json

This PR updates the Manifest Testnet chain name to include `Testnet`.

chore: update manifest testnet chain name

---

cosmos/qubetics_9003.json

This PR renames the chain to qubetics alpha testnet to maintain clear distinction between the  testnets.

chore:adds alpha keyword for alpha testnet

---

cosmos/xrplevm_1449000.json

This PR corrects the naming of the testnet chain in the registry file. The chain name was previously listed as "XRPLEVM Testnet" and has been updated to "XRPL EVM Testnet" to reflect the proper naming convention.
- Updated `chainName` in `cosmos/xrplevm_1449000.json` from "XRPLEVM Testnet" to "XRPL EVM Testnet".
- Removed any duplicate or erroneous entries related to the chain name.
- Delete coinGeckoId currency and currency fee so it does not show a $ value.
Accurate chain naming ensures that the testnet is correctly identified by developers and users. This change helps maintain consistency across our documentation and configuration, reducing any potential confusion.
- Verify that the JSON file displays the correct chain name.
- Ensure that any tools or scripts which rely on the chain …

fix: update XRPL EVM Testnet chain name in registry

---

cosmos/neutron.json
cosmos/pion.json

walletUrlForStaking를 neutron에 추가했습니다.
실제 뉴트론 업그레이드 이후 staking 모듈이 뉴트론에 생겼을때 해당 pr이 머지되어야 합니다.

[feat] add walletUrlForStaking on neutron

---

cosmos/seda-1-testnet.json

This PR updates the gasPriceStep values for the SEDA testnet in the Keplr chain registry to match those used in the SEDA mainnet for consistency.

Update seda testnet gas fee tiers

---

cosmos/gardia.json

This PR will upgrade the gardia chain-id to `gardia-9`.

bump: gardia testnet chain-id

---

cosmos/atomone-testnet.json
cosmos/atomone.json

Move PHOTON to the first position in the `feeCurrencies` array so that it is suggested first.

AtomeOne PHOTON fee priority

---

cosmos/thorchain.json

This PR fixes the token denominations for the new app-layer tokens on Thorchain. Incorrect denominations were causing these tokens not to appear in Keplr.
- Updates the `coinMinimalDenoms` for the following tokens: `thor.nami`, `thor.lqdy`, `thor.auto`, and `x/ruji`.
- The incorrect denominations prevented proper display and integration in wallets like Keplr.
You can verify the correct denominations by running:
```sh
thornode query bank total-supply --node https://rpc.ninerealms.com
```
You should see output similar to:
```sh
- amount: "5647240883825800"
denom: thor.nami
- amount: "101839819512800"
denom: thor.lqdy
- amount: "1581613991529600"
denom: thor.auto
- amount: "10000000000000000"
denom: x/ruji
```

fix: update coinMinimalDenoms for Thorchain app-layer tokens

---

cosmos/thorchain.json

Recently TCY and RUJI was added to Coingecko so adding ids now

Adding coingeckoids for TCY and RUJI to fetch prices

---

cosmos/manifest-ledger-mainnet.json
cosmos/manifest-ledger-testnet.json

This pull request updates contact information for the node provider in both the mainnet and testnet configuration files for the Manifest Ledger. The email address has been changed to reflect the new contact domain.
Changes to contact information:
* [`cosmos/manifest-ledger-mainnet.json`](diffhunk://#diff-d33db0ce7aa545bab439cd47b0477ea6216006333a76748158582ff9bbd1701dL9-R9): Updated the node provider's email address from `infra@liftedinit.org` to `hello@manifest.network`.
* [`cosmos/manifest-ledger-testnet.json`](diffhunk://#diff-6419de1671d356ad14c0d2fbe47cbe0bfa9284457f78f69c6d4db6011501dadcL9-R9): Updated the node provider's email address from `infra@liftedinit.org` to `hello@manifest.network`.

chore: update manifest email

---

cosmos/pulsar.json

The current endpoints stopped being supported a few months ago, this PR replaces them with the current endpoints.

Update Secret Testnet RPC/LCD endpoints

---

evm/eip155:10.json
evm/eip155:130.json
evm/eip155:81457.json
evm/eip155:8453.json

- 참조: https://github.com/ethereum-optimism/superchain-registry/blob/main/CHAINS.md
- superchain registry에 등록 안된 op stack chains: blast, derive

Add missing chain feature for op stack chains
